server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
aws:
  region: ${AWS_REGION:ap-northeast-2}
  profile: wish
  dynamodb:
    table-name: ${DDB_TABLE_NAME:AsyncEventTable}

logging:
  level:
    root: INFO
    software.amazon.awssdk: INFO
    com.team.async: DEBUG

ddb:
  table-name: AsyncEventTable

sqs:
  queue-url: ${SQS_QUEUE_URL:https://sqs.ap-northeast-2.amazonaws.com/590807098068/AsyncEventMainQueue}

security:
  jwt:
    secret: "X8jK9qL2zN5pW1rT4vY7xB3mC6hF0gD8sA1kE2oU3iR4tV9wQ5yZ6nJ0"
    ttl-seconds: 3600
